export const CHARACTERS_LOAD = 'CHARACTERS_LOAD'
export const CHARACTERS_LOAD_FULFILLED = 'CHARACTERS_LOAD_FULFILLED'

export const CHARACTERS_LOAD_MORE = 'CHARACTERS_LOAD_MORE'
export const CHARACTERS_LOAD_MORE_FULFILLED = 'CHARACTERS_LOAD_MORE_FULFILLED'

export const CHARACTERS_CHANGE_QUERY = 'CHARACTERS_CHANGE_QUERY'
export const CHARACTERS_UPDATE_NAME_STARTS_WITH = 'CHARACTERS_UPDATE_NAME_STARTS_WITH'

export const CHARACTERS_LOAD_MORE_LIMIT = 12
export const CHARACTERS_ORDER_NAME_ASC = 'name'
