export const COMICS_LOAD = 'COMICS_LOAD'
export const COMICS_LOAD_FULFILLED = 'COMICS_LOAD_FULFILLED'

export const COMICS_LOAD_MORE = 'COMICS_LOAD_MORE'
export const COMICS_LOAD_MORE_FULFILLED = 'COMICS_LOAD_MORE_FULFILLED'

export const COMICS_CHANGE_QUERY = 'COMICS_CHANGE_QUERY'
export const COMICS_UPDATE_TITLE_STARTS_WITH = 'COMICS_UPDATE_TITLE_STARTS_WITH'

export const COMICS_LOAD_MORE_LIMIT = 12
export const COMICS_ORDER_TITLE_ASC = 'title'
export const COMICS_ORDER_ON_SALE_DATE_DESC = '-onsaleDate'
export const COMICS_ORDER_ISSUE_NUMBER_DESC = '-issueNumber'

export const COMICS_SEARCH_FETCH_CHARACTER_SUGGESTIONS = 'COMICS_SEARCH_FETCH_CHARACTER_SUGGESTIONS'
export const COMICS_SEARCH_FETCH_CHARACTER_SUGGESTIONS_FULFILLED = 'COMICS_SEARCH_FETCH_CHARACTER_SUGGESTIONS_FULFILLED'
export const COMICS_SEARCH_ADD_CHARACTER_SUGGESTION = 'COMICS_SEARCH_ADD_CHARACTER_SUGGESTION'
export const COMICS_SEARCH_DELETE_CHARACTER_SUGGESTION = 'COMICS_SEARCH_DELETE_CHARACTER_SUGGESTION'
