export const COMICS_LOADING_STARTED = 'COMICS_LOADING_STARTED'

export const COMICS_LOAD = 'COMICS_LOAD'
export const COMICS_LOAD_SUCCESS = 'COMICS_LOAD_SUCCESS'

export const COMICS_LOAD_MORE = 'COMICS_LOAD_MORE'
export const COMICS_LOAD_MORE_SUCCESS = 'COMICS_LOAD_MORE_SUCCESS'

export const COMICS_CHANGE_SORT_ORDER = 'COMICS_CHANGE_SORT_ORDER'
export const COMICS_CHANGE_SORT_ORDER_SUCCESS = 'COMICS_CHANGE_SORT_ORDER_SUCCESS'

export const COMICS_LOAD_MORE_LIMIT = 6
export const COMICS_ORDER_TITLE_ASC = 'title'
export const COMICS_ORDER_ON_SALE_DATE_DESC = '-onsaleDate'
export const COMICS_ORDER_ISSUE_NUMBER_DESC = '-issueNumber'
