export const CREATORS_LOAD = 'CREATORS_LOAD'
export const CREATORS_LOAD_FULFILLED = 'CREATORS_LOAD_FULFILLED'

export const CREATORS_LOAD_MORE = 'CREATORS_LOAD_MORE'
export const CREATORS_LOAD_MORE_FULFILLED = 'CREATORS_LOAD_MORE_FULFILLED'

export const CREATORS_CHANGE_QUERY = 'CREATORS_CHANGE_QUERY'
export const CREATORS_UPDATE_NAME_STARTS_WITH = 'CREATORS_UPDATE_NAME_STARTS_WITH'

export const CREATORS_LOAD_MORE_LIMIT = 12
export const CREATORS_ORDER_FIRSTNAME_ASC = 'firstName'

export const CREATORS_DETAILS_LOAD = 'CREATORS_DETAILS_LOAD'
export const CREATORS_DETAILS_LOAD_FULFILLED = 'CREATORS_DETAILS_LOAD_FULFILLED'
export const CREATORS_DETAILS_SELECT = 'CREATORS_DETAILS_SELECT'